services:
    influxdb:
        image: influxdb:2.0.7
        environment:
            DOCKER_INFLUXDB_INIT_MODE: setup
            DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
            DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
            DOCKER_INFLUXDB_INIT_ORG: iot
            DOCKER_INFLUXDB_INIT_BUCKET: users_business_events
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
        ports:
        - "8086:8086"
    postgresql:
        image: postgres:15.1
        hostname: postgresql
        container_name: postgresDB
        volumes:
        - pg_data:/var/lib/postgresql/data
        environment:
            PGDATA: "/var/lib/postgresql/data"
            POSTGRES_DB: "core_dev"
            POSTGRES_USER: "core"
            POSTGRES_PASSWORD: "pass1234"
            POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
        ports:
        - "5432:5432"
    conduktor-platform:
        image: conduktor/conduktor-platform:1.19.2
        depends_on:
            - postgresql
            - redpanda-0
        ports:
            - "8080:8080"
        volumes:
            - conduktor_data:/var/conduktor
        environment:
            CDK_DATABASE_URL: "postgresql://conduktor:change_me@postgresql:5432/conduktor-platform"
            CDK_CLUSTERS_0_ID: "local-kafka"
            CDK_CLUSTERS_0_NAME: "local-kafka"
            CDK_CLUSTERS_0_BOOTSTRAPSERVERS: "redpanda-0:9092"
            CDK_CLUSTERS_0_SCHEMAREGISTRY_URL: "http://redpanda-0:18081"
            CDK_CLUSTERS_0_COLOR: "#6A57C8"
            CDK_CLUSTERS_0_ICON: "kafka"
            CDK_CLUSTERS_1_ID: "cdk-gateway"
            CDK_CLUSTERS_1_NAME: "cdk-gateway"
            CDK_CLUSTERS_1_BOOTSTRAPSERVERS: "conduktor-gateway:6969"
            CDK_CLUSTERS_1_SCHEMAREGISTRY_URL: "http://redpanda-0:18081"
            CDK_CLUSTERS_1_KAFKAFLAVOR_URL: "http://conduktor-gateway:8888"
            CDK_CLUSTERS_1_KAFKAFLAVOR_USER: "admin"
            CDK_CLUSTERS_1_KAFKAFLAVOR_PASSWORD: "conduktor"
            CDK_CLUSTERS_1_KAFKAFLAVOR_VIRTUALCLUSTER: "passthrough"
            CDK_CLUSTERS_1_KAFKAFLAVOR_TYPE: "Gateway"
            CDK_CLUSTERS_1_COLOR: "#6A57C8"
            CDK_CLUSTERS_1_ICON: "dog"
            CDK_MONITORING_CORTEX-URL: http://conduktor-monitoring:9009/
            CDK_MONITORING_ALERT-MANAGER-URL: http://conduktor-monitoring:9010/
            CDK_MONITORING_CALLBACK-URL: http://conduktor-platform:8080/monitoring/api/
            CDK_MONITORING_NOTIFICATIONS-CALLBACK-URL: http://localhost:8080

    conduktor-monitoring:
        image: conduktor/conduktor-platform-cortex:1.19.2
        environment:
            CDK_CONSOLE-URL: "http://conduktor-platform:8080"

    redpanda-0:
        command:
        - redpanda
        - start
        - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
        # Address the broker advertises to clients that connect to the Kafka API.
        # Use the internal addresses to connect to the Redpanda brokers'
        # from inside the same Docker network.
        # Use the external addresses to connect to the Redpanda brokers'
        # from outside the Docker network.
        - --advertise-kafka-addr internal://redpanda-0:9092,external://localhost:19092
        - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
        # Address the broker advertises to clients that connect to the HTTP Proxy.
        - --advertise-pandaproxy-addr internal://redpanda-0:8082,external://localhost:18082
        - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
        # Redpanda brokers use the RPC API to communicate with eachother internally.
        - --rpc-addr redpanda-0:33145
        - --advertise-rpc-addr redpanda-0:33145
        # Tells Seastar (the framework Redpanda uses under the hood) to use 1 core on the system.
        - --smp 1
        # The amount of memory to make available to Redpanda.
        - --memory 1G
        # Mode dev-container uses well-known configuration properties for development in containers.
        - --mode dev-container
        # enable logs for debugging.
        - --default-log-level=debug
        image: docker.redpanda.com/redpandadata/redpanda:v23.2.17
        container_name: redpanda-0
        healthcheck:
            test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"]
            interval: 15s
            timeout: 3s
            retries: 5
            start_period: 5s
            
        volumes:
        - redpanda-0:/var/lib/redpanda/data
        networks:
        - redpanda_network
        ports:
        - 18081:18081
        - 18082:18082
        - 19092:19092
        - 19644:9644

    console:
        container_name: redpanda-console
        image: docker.redpanda.com/redpandadata/console:v2.3.8
        networks:
        - redpanda_network
        entrypoint: /bin/sh
        command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
        environment:
            CONFIG_FILEPATH: /tmp/config.yml
            CONSOLE_CONFIG_FILE: |
                kafka:
                    brokers: ["redpanda-0:9092"]
                    schemaRegistry:
                        enabled: true
                        urls: ["http://redpanda-0:8081"]
                redpanda:
                    adminApi:
                        enabled: true
                        urls: ["http://redpanda-0:9644"]
        ports:
        - 8088:8088
        depends_on:
        - redpanda-0

    conduktor-gateway:
        image: conduktor/conduktor-gateway:2.3.0
        hostname: conduktor-gateway
        container_name: conduktor-gateway
        environment:
            KAFKA_BOOTSTRAP_SERVERS: redpanda-0:9092
        ports:
            - "8888:8888"
        healthcheck:
            test: curl localhost:8888/health
            interval: 5s
            retries: 25
        depends_on:
            redpanda-0:
                condition: service_healthy

    conduktor-data-generator:
        image: conduktor/conduktor-data-generator:0.1
        container_name: conduktor-data-generator
        platform: linux/arm64/v8
        environment:
            KAFKA_BOOTSTRAP_SERVERS: conduktor-gateway:6969
            KAFKA_SCHEMA_REGISTRY_URL: http://redpanda-0:8081
            GATEWAY_ADMIN_API: http://conduktor-gateway:8888
            restart: on-failure
        depends_on:
            redpanda-0:
                condition: service_healthy
            conduktor-gateway:
                condition: service_healthy
networks:
  redpanda_network:
    driver: bridge
volumes:
  pg_data: {}
  conduktor_data: {}
  redpanda-0: null
  